/*********************************************************
   DllData file -- generated by MIDL compiler 

        DO NOT ALTER THIS FILE

   This file is regenerated by MIDL on every IDL file compile.

   To completely reconstruct this file, delete it and rerun MIDL
   on all the IDL files in this DLL, specifying this file for the
   /dlldata command line option

*********************************************************/

#define PROXY_DELEGATION

#include <rpcproxy.h>

#ifdef __cplusplus
extern "C"   {
#endif

EXTERN_PROXY_FILE( IEnumTestSuiteItems )
EXTERN_PROXY_FILE( IEnumTestSuites )
EXTERN_PROXY_FILE( ITest )
EXTERN_PROXY_FILE( ITestOutput )
EXTERN_PROXY_FILE( ITestSuite )
EXTERN_PROXY_FILE( ITestSuiteCollection )
EXTERN_PROXY_FILE( ITestSuiteItem )
EXTERN_PROXY_FILE( ITestSuiteItemCollection )
EXTERN_PROXY_FILE( TestCore )
EXTERN_PROXY_FILE( cvIEnumTestSuiteItems )
EXTERN_PROXY_FILE( cvIEnumTestSuites )
EXTERN_PROXY_FILE( cvITest )
EXTERN_PROXY_FILE( cvITestOutput )
EXTERN_PROXY_FILE( cvITestSuite )
EXTERN_PROXY_FILE( cvITestSuiteCollection )
EXTERN_PROXY_FILE( cvITestSuiteItem )
EXTERN_PROXY_FILE( cvITestSuiteItemCollection )


PROXYFILE_LIST_START
/* Start of list */
  REFERENCE_PROXY_FILE( IEnumTestSuiteItems ),
  REFERENCE_PROXY_FILE( IEnumTestSuites ),
  REFERENCE_PROXY_FILE( ITest ),
  REFERENCE_PROXY_FILE( ITestOutput ),
  REFERENCE_PROXY_FILE( ITestSuite ),
  REFERENCE_PROXY_FILE( ITestSuiteCollection ),
  REFERENCE_PROXY_FILE( ITestSuiteItem ),
  REFERENCE_PROXY_FILE( ITestSuiteItemCollection ),
  REFERENCE_PROXY_FILE( TestCore ),
  REFERENCE_PROXY_FILE( cvIEnumTestSuiteItems ),
  REFERENCE_PROXY_FILE( cvIEnumTestSuites ),
  REFERENCE_PROXY_FILE( cvITest ),
  REFERENCE_PROXY_FILE( cvITestOutput ),
  REFERENCE_PROXY_FILE( cvITestSuite ),
  REFERENCE_PROXY_FILE( cvITestSuiteCollection ),
  REFERENCE_PROXY_FILE( cvITestSuiteItem ),
  REFERENCE_PROXY_FILE( cvITestSuiteItemCollection ),
/* End of list */
PROXYFILE_LIST_END


DLLDATA_ROUTINES( aProxyFileList, GET_DLL_CLSID )

#ifdef __cplusplus
}  /*extern "C" */
#endif

/* end of generated dlldata file */
